# Generated by Django 5.2.8 on 2025-12-11 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamLibraryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_data', models.JSONField(default=list, help_text='Steam 라이브러리 게임 목록 JSON')),
                ('total_games', models.IntegerField(default=0)),
                ('total_playtime_hours', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steam_library_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Steam 라이브러리 캐시',
                'verbose_name_plural': 'Steam 라이브러리 캐시',
            },
        ),
    ]
