# Generated by Django 5.2.8 on 2025-12-19 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_onboardingstatus_gamerating_gamesimilarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='similar_users',
            field=models.ManyToManyField(blank=True, help_text='SNS/팔로우 추천용. 메인 게임 추천은 GameSimilarity 사용', to=settings.AUTH_USER_MODEL, verbose_name='유사 취향 유저'),
        ),
    ]
