# Generated by Django 5.2.8 on 2025-12-19 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_options_alter_game_genre_tag_game_tags_and_more'),
        ('users', '0005_alter_user_similar_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0, verbose_name='유사도 점수')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='계산 시점')),
            ],
            options={
                'verbose_name': '유저 유사도',
                'verbose_name_plural': '유저 유사도',
            },
        ),
        migrations.RemoveIndex(
            model_name='gamesimilarity',
            name='users_games_game_a__5cb251_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamesimilarity',
            name='users_games_game_b__78010b_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='similar_users',
        ),
        migrations.AddField(
            model_name='gamesimilarity',
            name='similarity_rank',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='해당 게임 기준 유사도 순위 (1이 가장 유사)', verbose_name='유사도 순위'),
        ),
        migrations.AlterField(
            model_name='gamesimilarity',
            name='game_a',
            field=models.ForeignKey(help_text='항상 game_b보다 작은 ID', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_from', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gamesimilarity',
            name='game_b',
            field=models.ForeignKey(help_text='항상 game_a보다 큰 ID', on_delete=django.db.models.deletion.CASCADE, related_name='similarity_to', to='games.game'),
        ),
        migrations.AddIndex(
            model_name='gamesimilarity',
            index=models.Index(fields=['game_a', 'similarity_rank'], name='users_games_game_a__f3f0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesimilarity',
            index=models.Index(fields=['game_b', 'similarity_rank'], name='users_games_game_b__2de6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesimilarity',
            index=models.Index(fields=['game_a', '-similarity_score'], name='users_games_game_a__d5bd74_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesimilarity',
            index=models.Index(fields=['game_b', '-similarity_score'], name='users_games_game_b__6eb617_idx'),
        ),
        migrations.AddField(
            model_name='usersimilarity',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersimilarity',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersimilarity',
            index=models.Index(fields=['from_user', '-similarity_score'], name='users_users_from_us_3c53da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersimilarity',
            unique_together={('from_user', 'to_user')},
        ),
    ]
