# Generated by Django 5.2.8 on 2025-12-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersimilarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerating',
            name='comment',
            field=models.TextField(blank=True, help_text='선택적 한줄평', verbose_name='코멘트'),
        ),
    ]
