# Generated by Django 5.2.8 on 2025-12-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rating_content_rating_created_at_rating_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='metacritic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preview_url', models.URLField(max_length=500)),
                ('data_480', models.URLField(max_length=500)),
                ('data_max', models.URLField(max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='games.game')),
            ],
        ),
    ]
