# Generated by Django 5.2.8 on 2025-12-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_background_image_game_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedGameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('popular', '요즘 뜨는'), ('top_rated', '평점 높은'), ('new_releases', '신작 게임'), ('trending', '트렌딩'), ('upcoming', '출시 예정')], max_length=20, unique=True)),
                ('games_data', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Game List',
                'verbose_name_plural': 'Cached Game Lists',
            },
        ),
    ]
