# Generated by Django 5.2.8 on 2025-12-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_cachedgamelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '게임', 'verbose_name_plural': '게임'},
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, help_text='레거시 필드. tags 사용 권장', max_length=100),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그명')),
                ('slug', models.SlugField(help_text='URL/검색용 영문 식별자', unique=True, verbose_name='슬러그')),
                ('tag_type', models.CharField(choices=[('genre', '장르'), ('theme', '테마'), ('feature', '특징'), ('mood', '분위기')], default='genre', max_length=20, verbose_name='태그 유형')),
                ('weight', models.FloatField(default=1.0, help_text='추천 계산 시 중요도 (기본 1.0)', verbose_name='가중치')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'indexes': [models.Index(fields=['slug'], name='games_tag_slug_b581bf_idx'), models.Index(fields=['tag_type'], name='games_tag_tag_typ_3ade3c_idx')],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='장르/테마/특징 태그 (추천 계산에 사용)', related_name='games', to='games.tag'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['steam_appid'], name='games_game_steam_a_7c3043_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rawg_id'], name='games_game_rawg_id_471fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['metacritic_score'], name='games_game_metacri_14be54_idx'),
        ),
    ]
