# Generated by Django 5.2.8 on 2025-12-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_options_alter_game_genre_tag_game_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_kr',
            field=models.TextField(blank=True, help_text='한국어 설명 (AI 번역)'),
        ),
    ]
