# Generated by Django 5.2.8 on 2025-12-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_description_kr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_author_id', models.CharField(max_length=50, verbose_name='Steam 작성자 ID')),
                ('author_playtime_hours', models.IntegerField(default=0, verbose_name='작성자 플레이 시간(시간)')),
                ('author_playtime_at_review', models.IntegerField(default=0, verbose_name='리뷰 작성 시점 플레이 시간(시간)')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('is_recommended', models.BooleanField(default=True, verbose_name='추천 여부')),
                ('votes_up', models.IntegerField(default=0, verbose_name='유용함 투표수')),
                ('votes_funny', models.IntegerField(default=0, verbose_name='웃김 투표수')),
                ('steam_review_id', models.CharField(max_length=50, unique=True, verbose_name='Steam 리뷰 ID')),
                ('timestamp_created', models.DateTimeField(blank=True, null=True, verbose_name='작성 시간')),
                ('timestamp_updated', models.DateTimeField(blank=True, null=True, verbose_name='수정 시간')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='크롤링 시간')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steam_reviews', to='games.game')),
            ],
            options={
                'verbose_name': 'Steam 리뷰',
                'verbose_name_plural': 'Steam 리뷰',
                'ordering': ['-votes_up', '-crawled_at'],
                'indexes': [models.Index(fields=['game', '-votes_up'], name='games_steam_game_id_c5eade_idx'), models.Index(fields=['game', 'is_recommended'], name='games_steam_game_id_163a20_idx')],
            },
        ),
    ]
