# Generated by Django 5.2.8 on 2025-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_steamreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_on_gamepass',
            field=models.BooleanField(default=False, help_text='Xbox Game Pass에 포함된 게임', verbose_name='게임패스 포함'),
        ),
    ]
