# Generated by Django 5.2.8 on 2025-12-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rating_content_rating_created_at_rating_updated_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='games.game'),
        ),
    ]
