# Generated by Django 5.2.8 on 2025-12-11 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_background_image_game_description_and_more'),
        ('users', '0003_steamlibrarycache'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '시작 안함'), ('in_progress', '진행 중'), ('completed', '완료'), ('skipped', '건너뜀')], default='not_started', max_length=20, verbose_name='상태')),
                ('current_step', models.IntegerField(default=0, verbose_name='현재 단계')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='총 평가 수')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '온보딩 상태',
                'verbose_name_plural': '온보딩 상태',
            },
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(choices=[(-1, '역따봉'), (0, '스킵'), (3.5, '따봉'), (5, '쌍따봉')], verbose_name='평점')),
                ('is_onboarding', models.BooleanField(default=False, verbose_name='온보딩 평가 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게임 평가',
                'verbose_name_plural': '게임 평가',
                'indexes': [models.Index(fields=['user', 'score'], name='users_gamer_user_id_c3f998_idx'), models.Index(fields=['game', 'score'], name='users_gamer_game_id_84d5d4_idx')],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(verbose_name='유사도 점수')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('game_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_from', to='games.game')),
                ('game_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_to', to='games.game')),
            ],
            options={
                'verbose_name': '게임 유사도',
                'verbose_name_plural': '게임 유사도',
                'indexes': [models.Index(fields=['game_a', 'similarity_score'], name='users_games_game_a__5cb251_idx'), models.Index(fields=['game_b', 'similarity_score'], name='users_games_game_b__78010b_idx')],
                'unique_together': {('game_a', 'game_b')},
            },
        ),
    ]
